### ISSUE TITLE
<US 05.01.01> As a player, I want to search for other players by username.

### ISSUE THREAD

**Issue by michehwl** [CMPUT301W22T31/QRAdventure#24]
Goal: a player is searchable by their username

**Comment by tradke** [comment]
This issue related to these wiki pages: 
[Backlog](https://github.com/CMPUT301W22T31/QRAdventure/wiki/Product-Backlog#:~:text=Searching-,Type,-Information)
[summary](https://github.com/CMPUT301W22T31/QRAdventure/wiki/Backlog:-Expected-Deliverables-for-Part-3#:~:text=Search%20for%20others%20via%20username)
