### ISSUE TITLE
Intent Unit testing

### ISSUE THREAD

**Issue by JackOpgenorth** [CMPUT301W22T31/QRAdventure#54]
Alexander said we should have at least 1 intent unit test in the last meeting. (I think we might need more, but that will probably become more clear as we implement them)

**Comment by tradke** [comment]
Going to try to make 2 intent tests along these lines (subject to change)
1) Launch > (Login - existing account) > visit account > visit scan (Scan a QR) > add the QR, redirects to account > my codes > visit code page
2) Launch > (Login - existing account) > visit leaderboard > visit search > input name and click on result > visit profile > view codes > visit code page

I'm not sure yet how the intent test will handle the camera scan, but we'll cross that bridge when we get there.

**Comment by tradke** [comment]
related branch: https://github.com/CMPUT301W22T31/QRAdventure/tree/tyler/intent-test
